import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";

import Nav from "../components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ colorScheme: "light dark" }}>
      <body
        style={{
          backgroundColor: "var(--background)",
          width: "100%",
          height: "100%",
          margin: 0,
          minHeight: "100vh",
        }}
      >
        <Theme
          accentColor="sky"
          grayColor="gray"
          panelBackground="solid"
          scaling="100%"
          radius="full"
          appearance="inherit"
        >
          <Nav />
          {children}
        </Theme>
      </body>
    </html>
  );
}
